### ISSUE TITLE
There should be more precise installation requirements

### ISSUE THREAD

**Issue by jindrichmarek** [alberto-solano/open-source-LLM-translation-tool#1]
Thanks for your work, I really like it.

In the installation instructions, I think it would be more precise to mention that **Python 3.9** (or probably alternatively 3.8, which I have not tested) is required. BTW, it is also possible to create a virtual environment using `conda`:
`conda create --name ostt python=3.9`
`conda activate ostt`

I did not have `rust` in my environment, so the installation crashed and I had to install `rustup` first. Maybe that should be mentioned as well?

Also, the approximate size of the files downloaded during the installation should be mentioned.

**Comment by alberto-solano** [comment]
Hi!

You are right! I added a Python version matching the requirements which runs on the AWS EC2 with Ubuntu that I've using and also I have provided a new branch for running it into Windows. Also update the readme. I have also included a .txt file with the necessary libraries in case you want to use another python version.

Thank you!
